apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-manager
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: harness-manager
